const dev = {
    MSG_ARE_U_SURE: "Esta seguro?",
    CERO: 0,
    PRODUCT_GROUP_BRUSHWORK: "Pintura",
    PRODUCT_GROUP_SANPAPER: "Lija",
    PRODUCT_GROUP_ORDER: "Otros",
    PRODUCT_CATEGORY_INSUMOS: "Insumo",
    PRODUCT_TYPE_SERVICE: "Servicio",
    PRODUCT_TYPE_STORE: "Repuesto",
    PRODUCT_TYPE_MATERIAL: "Material",
    IVG: 1.18,
    PREFIX_QUOTEID: "CT",
    ICON_UNICODE_INFO: "[ \u2139 ]",
    ICON_UNICODE_WARNING: "\u26A0",
    ICON_UNICODE_OK: "[ \u2714 ]",
    ICON_UNICODE_ERROR: "[ \u2716 ]",
    ICON_UNICODE_QUESTION : "[ \u003F ]",
    API_URL_HTTP:"http://localhost:9090",// "https://angularivanapp.herokuapp.com",//"https://bodyworks-api.herokuapp.com",
    API_URL_WS: "ws://localhost:9090",//"wss://angularivanapp.herokuapp.com",//"wss://bodyworks-api.herokuapp.com",
    STATUS_ACEPTED: "Aceptado",
    ROLE_ADNISTRATOR: "Administrador",
    STATUS_FINISHED: "Terminado",
};

const prod = {
    MSG_ARE_U_SURE: "Esta seguro?",
    CERO: 0,
    PRODUCT_GROUP_BRUSHWORK: "Pintura",
    PRODUCT_GROUP_SANPAPER: "Lija",
    PRODUCT_GROUP_ORDER: "Otros",
    PRODUCT_CATEGORY_INSUMOS: "Insumo",
    PRODUCT_TYPE_SERVICE: "Servicio",
    PRODUCT_TYPE_STORE: "Repuesto",
    PRODUCT_TYPE_MATERIAL: "Material",
    IVG: 1.18,
    PREFIX_QUOTEID: "CT",
    ICON_UNICODE_INFO: "[ \u2139 ]",
    ICON_UNICODE_WARNING: "\u26A0",
    ICON_UNICODE_OK: "[ \u2714 ]",
    ICON_UNICODE_ERROR: "[ \u2716 ]",
    ICON_UNICODE_QUESTION : "[ \u003F ]",
    API_URL_HTTP: "https://angularivanapp.herokuapp.com",//"https://bodyworks-api.herokuapp.com",
    API_URL_WS: "wss://angularivanapp.herokuapp.com",//"wss://bodyworks-api.herokuapp.com",
    STATUS_ACEPTED: "Aceptado",
    ROLE_ADNISTRATOR: "Administrador",
    STATUS_FINISHED: "Terminado",
};

//export const constantes = process.env.NODE_ENV === "development" ? dev : prod;
export const constantes =  prod;
